// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUBv_z7zqohpkLW-XjSSDOCmSqDgvobaY',
    appId: '1:869361773034:web:241e2be031cde72bd0aa93',
    messagingSenderId: '869361773034',
    projectId: 'authexample-9c207',
    authDomain: 'authexample-9c207.firebaseapp.com',
    storageBucket: 'authexample-9c207.firebasestorage.app',
    measurementId: 'G-ZKDKT4FG9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjNDT0QfbA7la30W03RMue0mNj77aXCVk',
    appId: '1:869361773034:android:151bdf3f55ab8990d0aa93',
    messagingSenderId: '869361773034',
    projectId: 'authexample-9c207',
    storageBucket: 'authexample-9c207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInvo2hTw1IV0j-hq-vdYII_iCzNqUCio',
    appId: '1:869361773034:ios:86f95ad568d029fcd0aa93',
    messagingSenderId: '869361773034',
    projectId: 'authexample-9c207',
    storageBucket: 'authexample-9c207.firebasestorage.app',
    androidClientId: '869361773034-emirgi69sbgpl5m6riclngah34o1ukoj.apps.googleusercontent.com',
    iosClientId: '869361773034-1fdqphp61nnrvude4fk1kvm8k8np9ive.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInvo2hTw1IV0j-hq-vdYII_iCzNqUCio',
    appId: '1:869361773034:ios:86f95ad568d029fcd0aa93',
    messagingSenderId: '869361773034',
    projectId: 'authexample-9c207',
    storageBucket: 'authexample-9c207.firebasestorage.app',
    androidClientId: '869361773034-emirgi69sbgpl5m6riclngah34o1ukoj.apps.googleusercontent.com',
    iosClientId: '869361773034-1fdqphp61nnrvude4fk1kvm8k8np9ive.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUBv_z7zqohpkLW-XjSSDOCmSqDgvobaY',
    appId: '1:869361773034:web:3abbff2cbe9d450cd0aa93',
    messagingSenderId: '869361773034',
    projectId: 'authexample-9c207',
    authDomain: 'authexample-9c207.firebaseapp.com',
    storageBucket: 'authexample-9c207.firebasestorage.app',
    measurementId: 'G-578ZPE5X8P',
  );
}
